set_property SRC_FILE_INFO {cfile:D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/constrs_1/new/IO.xdc rfile:../../../CPU_IP.srcs/constrs_1/new/IO.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T21 [get_ports full_tag_counter]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports zero_tag_timer]
