# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.cache/wt [current_project]
set_property parent.project_path D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths d:/ZedBorad/zedboard_programmes/ip_repo [current_project]
add_files D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/imports/MIPS_FPGA/IM.coe
add_files D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/imports/MIPS_FPGA/DM.coe
add_files D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/bd/design_1/ip/design_1_dist_mem_gen_0_1/design_1_dist_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/bd/design_1/ip/design_1_dist_mem_gen_1_0/design_1_dist_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib {
  D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/imports/MIPS_FPGA/counter_timer.v
  D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/imports/MIPS_FPGA/frequency.v
  D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/constrs_1/new/IO.xdc
set_property used_in_implementation false [get_files D:/ZedBorad/zedboard_programmes/CPU_IP/CPU_IP.srcs/constrs_1/new/IO.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg484-1 -flatten_hierarchy none -keep_equivalent_registers -no_lc


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
